version: '2'
services:
  proxy:
    image: nginx:stable
    restart: always
    network_mode: bridge
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
      - error_pages.conf:/etc/nginx/error_pages.conf:ro
      - conf.d:/etc/nginx/conf.d:ro
      - error_pages:/var/www/html:ro
      - ssl/default:/etc/nginx/cert:ro
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
  letsencrypt:
    image: jkpark/docker-letsencrypt_route53
    restart: always
    network_mode: bridge
    volumes:
      - ssl:/etc/letsencrypt/archive
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AWS_ACCESS_KEY=AWS_ROUTE53_ACCESSKEY
      - AWS_SECRET_KEY=AWS_ROUTE53_SECRETKEY
      - EMAIL=EMAIL_ADDRESS
      - DNS_LIST=DNS(seprated comma and support wild card)
